### ISSUE TITLE
bme doesn't respect configured control state

### ISSUE THREAD

**Issue by npry** [pchwalek/env_glasses#1] opened 2023-12-09 08:21 UTC
## summary

The bme task doesn't respect the configured control / enablement state -- even if it's notionally disabled, I still get bme packets. As far as I've seen, it's the only sensor that does this.

Low urgency, just recording the observation.

## repro

- Send a control packet with `bme688` set to `false`
- Firmware replies with a state update with `bme688` set to `false`
- Continue to receive bme packets regardless

For all sensors, it can take a few seconds (up to 15s or so for high-throughput sensors like imu) for the packet buffers to empty on the glasses / to actually stop receiving packets for the relevant sensor after disabling it, so I wanted to cover the possibility that some version of this was happening here. This doesn't seem to be the case &mdash; I tested by just letting the glasses run for a few minutes after the disable message and was still seeing bme packets.

**Comment by pchwalek** [comment] 2023-12-10 00:40
The issue is caused by the BME task not checking for a termination condition, continuing perpetually from the initial start. The issue is resolved in the latest firmware.

**Closed as completed by pchwalek** 2023-12-10 00:40 UTC
